ref:
  as: osd-ccs-cluster-provision-admin-kubeconfig
  from: cli-ocm
  grace_period: 10m
  commands: osd-ccs-cluster-provision-admin-kubeconfig-commands.sh
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
  env:
  - name: OCM_LOGIN_ENV
    default: "staging"
    documentation: The environment for ocm login. The supported values are [production, staging].
  documentation: |-
    Using ocm cli to create an osd ccs AWS cluster with the provided cluster profile. The cluster profile should include the offline token ocm-token to login.
